"""Initial migration

Revision ID: 4a2d5b6ca081
Revises: 
Create Date: 2023-07-09 14:55:06.747367

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '4a2d5b6ca081'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nom', sa.String(length=50), nullable=False),
                    sa.Column('prenom', sa.String(length=50), nullable=False),
                    sa.Column('telephone', sa.String(length=15), nullable=True),
                    sa.Column('email', sa.String(length=100), nullable=False),
                    sa.Column('adresse', sa.String(length=100), nullable=True),
                    sa.Column('autoriser_publier_article', sa.Boolean(), nullable=True),
                    sa.Column('autoriser_commenter_article', sa.Boolean(), nullable=True),
                    sa.Column('login', sa.String(length=50), nullable=False),
                    sa.Column('mot_de_passe', sa.String(length=100), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('login')
                    )
    op.create_table('article',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('titre', sa.String(length=100), nullable=False),
                    sa.Column('introduction', sa.Text(), nullable=False),
                    sa.Column('manifestation', sa.Text(), nullable=False),
                    sa.Column('prevention', sa.Text(), nullable=False),
                    sa.Column('cause', sa.Text(), nullable=False),
                    sa.Column('audio', sa.String(length=100), nullable=True),
                    sa.Column('date_creation', sa.DateTime(), nullable=True),
                    sa.Column('image_article', sa.String(length=100), nullable=True),
                    sa.Column('auteur_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('commentaire',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('contenu', sa.Text(), nullable=False),
                    sa.Column('date_commentaire', sa.DateTime(), nullable=True),
                    sa.Column('auteur_id', sa.Integer(), nullable=True),
                    sa.Column('article_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
                    sa.ForeignKeyConstraint(['auteur_id'], ['utilisateur.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaire')
    op.drop_table('article')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
